import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ADMIN_USER_ID = os.getenv("ADMIN_USER_ID")
ADMIN_USER_PWD = os.getenv("ADMIN_USER_PWD")
ADMIN_USER_EMAIL = os.getenv("ADMIN_USER_EMAIL")
DB_URL = os.getenv("DB_URL")
SQL_DB_CREATION_QUERY_PATH = os.getenv("SQL_DB_CREATION_QUERY")
SQL_TABLE_CREATION_QUERY_PATH = os.getenv("SQL_TABLE_CREATION_QUERY")
SQL_ADMIN_CREATION_QUERY_PATH = os.getenv("SQL_ADMIN_CREATION_QUERY")
STARTING_BALANCE_FOR_A_NEW_USER = os.getenv("STARTING_BALANCE_FOR_A_NEW_USER")
